theme: jekyll-theme-hacker
title: Alwin Woo
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - README.md
  - github.md
  - ikigai.md
  - stocks.md
  - stocks/0008.md
  - stocks/0257.md
  - stocks/0857.md
  - stocks/1199.md
  - stocks/1288.md
  - stocks/1622.md
  - stocks/1778.md
  - stocks/1806.md
  - stocks/3988.md
